### ISSUE TITLE
Make dependencies clear on ReadMe page

### ISSUE THREAD

**Issue by BigBadaboom** [iamisti/mdDataTable#261]
I think it would be useful to new users if you listed the dependencies that mdDataTable required on the ReadMe page.

It took me a while to get this working because initially I just got the generic message 

    Failed to instantiate module adminApp due to:
    [$injector:modulerr]

In particular I needed to add

angular-sanitize
angular-material-icons
lodash
underscore?

**Comment by garretwilson** [comment]
Yes, I kept getting all sorts of messages like this as well. Finally I just switched to https://github.com/daniel-nagy/md-data-table, which has fewer dependencies.

If you would be clear about your dependencies, maybe I could get it working.

Another question: do you use the material icon images, or do you use the material icon font?

**Comment by mccoolaustinm** [comment]
Also having trouble with dependencies and basic configuration. I have lodash and angular-material-icons, and that eliminated the module loading errors. Now I am getting errors like:

```
angular.js:14328 TypeError: _.countBy is not a function 
at TableDataStorageService.TableDataStorageFactory.TableDataStorageService.getNumberOfSelectedRows (md-data-table.js:764)
at Scope.wrapper [as getNumberOfSelectedRows] (lodash.js:1157)
....
```

Underscore is not listed as a dependency, but I added it anyway and checked that _.countBy could be referenced. I'm not sure at this point whether the issue is with my table setup, which is a pretty straightforward ng-repeating directive. 

Edit: FIXED the above issue by using the exact versions of lodash and underscore referenced in the codepen examples... This may be a separate issue, but now getting:

```
angular.js:14328 TypeError: Cannot read property 'length' of undefined
    at $interpolate (angular.js:12719:16)
    at (md-data-table.js:1214:37) 
    .....
    at invokeLinkFn (angular.js:10252:9) <mdt-column class="ng-scope ng-isolate-scope">
```
