### ISSUE TITLE
Angular last version support

### ISSUE THREAD

**Issue by toonvanstrijp** [iamisti/mdDataTable#274]
I'm using angular 1.6.1 and it seems not to work with it:

`angular.js:14328 TypeError: Cannot read property 'length' of undefined
    at k (http://localhost:3000/bower_components/angular/angular.min.js:108:320)
    at http://localhost:3000/bower_components/md-data-table/dist/md-data-table.js:1214:37
    at http://localhost:3000/bower_components/angular/angular.min.js:60:109
    at http://localhost:3000/bower_components/angular/angular.min.js:65:281
    at d (http://localhost:3000/bower_components/angular/angular.min.js:62:252)
    at m (http://localhost:3000/bower_components/angular/angular.min.js:66:300)
    at Object.link (http://localhost:3000/bower_components/md-data-table/dist/md-data-table.js:1212:17)
    at http://localhost:3000/bower_components/angular/angular.min.js:16:71
    at http://localhost:3000/bower_components/angular/angular.min.js:83:480
    at ta (http://localhost:3000/bower_components/angular/angular.min.js:84:35) <mdt-column align-rule="left" class="ng-scope ng-isolate-scope">`

**Comment by ghost** [comment]
Hi ToonvanStrijp, I am using the package with angular 1.6.1, maybe it is something else

**Comment by stelllla** [comment]
I`m having the same issue with Angular 1.6.1. You can view an example here: http://codepen.io/anon/pen/BpLOoo/

Table header is not shown and if your data values are different from string - they are not shown as well.

**Comment by bspai** [comment]
@stelllla the fix for issue of _"if your data values are different from string - they are not shown as well"_  has been found. Please check this link https://github.com/iamisti/mdDataTable/issues/268 (I don't see this issue in your code pen link but In case if you are still having issue in local setup).
However I am still facing other issues listed.

**Comment by nojaf** [comment]
I'm having the same issue. All my columns are strings.

**Comment by Xyara** [comment]
Me too, using angular 1.6.1 and Typescript.
```
angular.js:14335TypeError: Cannot read property 'length' of undefined
    at $interpolate (http://localhost:3001/vendor.bundle.js:92356:16)
    at http://localhost:3001/vendor.bundle.js:134092:37
    at publicLinkFn (http://localhost:3001/vendor.bundle.js:88382:29)
    at lazyCompilation (http://localhost:3001/vendor.bundle.js:88774:25)
    at boundTranscludeFn (http://localhost:3001/vendor.bundle.js:88561:16)
    at controllersBoundTransclude (http://localhost:3001/vendor.bundle.js:89328:20)
    at Object.link (http://localhost:3001/vendor.bundle.js:134090:17)
    at http://localhost:3001/vendor.bundle.js:80928:18
    at http://localhost:3001/vendor.bundle.js:89883:44
    at invokeLinkFn (http://localhost:3001/vendor.bundle.js:89889:9) <mdt-column class="ng-scope ng-isolate-scope">
```

**Comment by VasylPosmit** [comment]
Have the same issue with 1.6.2.
Dropping to1.5.11 solves the issue

```
TypeError: Cannot read property 'length' of undefined
    at $interpolate (http://localhost.com/bower_components/angular/angular.js:12742:16)
    at http://localhost.com/bower_components/md-data-table/dist/md-data-table.js:1214:37
    at publicLinkFn (http://localhost.com/bower_components/angular/angular.js:8767:29)
    at lazyCompilation (http://localhost.com/bower_components/angular/angular.js:9159:25)
    at boundTranscludeFn (http://localhost.com/bower_components/angular/angular.js:8946:16)
    at controllersBoundTransclude (http://localhost.com/bower_components/angular/angular.js:9713:20)
    at Object.link (http://localhost.com/bower_components/md-data-table/dist/md-data-table.js:1212:17)
    at http://localhost.com/bower_components/angular/angular.js:1291:18
    at http://localhost.com/bower_components/angular/angular.js:10268:44
    at invokeLinkFn (http://localhost.com/bower_components/angular/angular.js:10274:9) <mdt-column ...
```

**Comment by erichutchinson** [comment]
Wrapping the column header name in a SPAN tag solved this issue for me. See Issue #259

**Comment by zuhrasofyan** [comment]
nice solution @erichutchinson 
The table rendered just fine now, but still, I've got this error in console:
```
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at append (http://localhost:3000/bower_components/angular/angular.js:3852:15)
    at JQLite.(anonymous function) [as append] (http://localhost:3000/bower_components/angular/angular.js:3968:17)
    at http://localhost:3000/bower_components/md-data-table/dist/md-data-table.js:1380:33
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:18010:23)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:18280:24)
    at done (http://localhost:3000/bower_components/angular/angular.js:12378:47)
    at completeRequest (http://localhost:3000/bower_components/angular/angular.js:12604:7)
    at XMLHttpRequest.requestLoaded (http://localhost:3000/bower_components/angular/angular.js:12532:9)
```
is there any fix around this?
