### ISSUE TITLE
mdt-column and mdt-cell not able to handle complex ng-repeat

### ISSUE THREAD

**Issue by mathiasconradt** [iamisti/mdDataTable#79]
I found two issues with ng-repeat in mdt-column and mdt-cell. They seem very related, so I put them into one ticket.
Both are a bit related to https://github.com/iamisti/mdDataTable/issues/68, but a different case though, therefore opening a new ticket.
I took the Demo table and wanted to replace the static column names with dynamic ones.

**(1) mdt-column and ng-repeat**

I added this to the controller:

```javascript
$scope.columns = [];
$scope.columns["nutritions"] = [
          {"title":"Dessert (100g serving)", "field":"name", "sortable":true}, 
          {"title":"Calories", "field":"calories", "sortable":true},
          {"title":"Fat (g)", "field":"fat", "sortable":true},
          {"title":"Carbs (g)", "field":"carbs", "sortable":true},
          {"title":"Protein (g)", "field":"protein", "sortable":true},
          {"title":"Sodium (mg)", "field":"sodium", "sortable":true},
          {"title":"Calcium (%)", "field":"calcium", "sortable":true},
          {"title":"Iron (%)", "field":"iron", "sortable":true}       
] 
```

and with this in html code, it works:

```html
<mdt-column align-rule="left" ng-repeat="column in columns['nutritions']">{{column.title}}</mdt-column>
```

but as soon as I add another reference field into the mdt-column tag body, it fails, i.e.:

```html
<mdt-column align-rule="left" ng-repeat="column in columns['nutritions']">{{column.title}} / {{column.field}}</mdt-column>
```

The header is not shown at all anymore.

CodePen for this example:
http://codepen.io/mathiasconradt/pen/ZQNrvM

**(2) mdt-cell and ng-repeat**

The other issue is when I also try to handle the mdt-cell fields dynamically via ng-repeat.

Based on above code base:

```html
<mdt-cell ng-repeat="column in columns['nutritions']">{{nutrition[column.field]}}</mdt-cell>  
```

The data values are not shown at all.

CodePen for this example:
http://codepen.io/mathiasconradt/pen/OMYQdj

Both ng-repeat code samples work fine when used with just a <div>-tag, but not with mdt-cell or mdt-column.

**Comment by faheemhameed** [comment]
I am having some similar issue:

Please see the following code 

```
    <mdt-table
        selectable-rows="true">

        <mdt-header-row>
            <mdt-column ng-repeat="fld in ['col1', 'col2', 'col3']">
                {{ fld }}
            </mdt-column>
        </mdt-header-row>

        <mdt-row ng-repeat="rowLink in [{title: 'aaaaa'}, {title: 'bbbbb'}, {title: 'ccccc'}]">
            <mdt-cell ng-repeat="i in [1, 2, 4]">
                {{i}}
            </mdt-cell>
        </mdt-row>
    </mdt-table>
```

The variable does <mdt-cell> does not print. It's just empty.

Also if we try     

```
            <mdt-cell ng-repeat="i in [1, 2, 4]">
                {{i}} - {{rowLink.title}}
            </mdt-cell>
```

There are other kind of errors. Please help with this.

**Comment by Gaglia88** [comment]
Hi,
I have the same issue, someone has figured out how to fix it?

I want to display an array of array, like:

 ```
[
 ['Name', intValue, ...],
 ['Name2', intValue2, ...],
 ...
]
```

But when I try to visualize it I cannot iterate on mdt-cell, it results always empty.
Also I tried to visualize the $index value

```
<mdt-table virtual-repeat="true">            
	<mdt-header-row>
		<mdt-column align-rule="left" ng-repeat="column in header">{{column}}</mdt-column>
	</mdt-header-row>
	<mdt-row ng-repeat="row in data">
		<mdt-cell ng-repeat="column in row track by $index">{{$index}}</mdt-cell>
	</mdt-row>
</mdt-table>
```

and the $index have always the value of the row, it doesn't increase with the column number, I mean in the first row I always see 0 0 0 0, in the second 1 1 1 1, and so on...

**Comment by Gaglia88** [comment]
Hi, I solved the problem in my case...
In the md-data-table.js on line 875 there is this assignment:
`var cellValue = $parse(clone.html().replace('{{', '').replace('}}', ''))($scope.$parent);`

How you can see it evaluates the function that you put in the mdt-cell using the scope of it's parent (mdt-row), thus it uses the scope of the row and it cannot find the variable 'column'...

So, If you modify the code in this way
`var cellValue = $parse(clone.html().replace('{{', '').replace('}}', ''))($scope);`
it uses the right scope and it able to read the 'column' variable.

**Comment by faheemhameed** [comment]
@Gaglia88 Thanks for your help... I fixed this as per your advise.

@iamisti  Can this be included in the next build? It would be really helpful.

Many thanks guys.

**Comment by iamisti** [comment]
Yes, it will be changes with $interpolate which will most probably solve this issue.

**Comment by faheemhameed** [comment]
Thanks @iamisti . Looking forward to it.


Another related issue is that if I add a empty mdt-column as below (the last 2 columns):

>         <mdt-header-row>
            <mdt-column ng-repeat="fld in currLinkObj.fields"
                ng-class="lus.getWidthClass(fld)"
                align-rule="left"
                column-definition="The total amount of food energy in the given serving size.">
                {% verbatim %}{{ fld.title }}{% endverbatim %}
            </mdt-column>
            <mdt-column ng-show="currLinkObj.hasEdit && currView == 'edit'"></mdt-column>
            <mdt-column ng-show="currLinkObj.hasDelete && currView == 'edit'"></mdt-column>
        </mdt-header-row>

then I get the following error

> vendors.js:28980 TypeError: Cannot read property 'indexOf' of undefined
>     at http://libra.localhost/js/vendors.js:118516:36
>     at publicLinkFn (http://libra.localhost/js/vendors.js:23559:29)
>     at lazyCompilation (http://libra.localhost/js/vendors.js:23904:25)
>     at boundTranscludeFn (http://libra.localhost/js/vendors.js:23697:16)
>     at controllersBoundTransclude (http://libra.localhost/js/vendors.js:24445:20)
>     at Object.link (http://libra.localhost/js/vendors.js:118513:17)
>     at http://libra.localhost/js/vendors.js:16307:18
>     at http://libra.localhost/js/vendors.js:24988:44
>     at invokeLinkFn (http://libra.localhost/js/vendors.js:24994:9)
>     at nodeLinkFn (http://libra.localhost/js/vendors.js:24395:11) <mdt-column ng-show="currLinkObj.hasEdit &amp;&amp; currView == 'edit'" class="ng-scope ng-isolate-scope">


I have to insert a dot (not even &nbsp;) and make it's color white to fix this issue

**Comment by faheemhameed** [comment]
Another related issue is that if I use an ng-repeat for <mdt-column> and then add some more <mdt-column> without ng-repeat then then it puts the later <mdt-column> at the beginning instead of at the end 


>         <mdt-header-row>
>             <mdt-column ng-repeat="fld in currLinkObj.fields"
>                 ng-class="lus.getWidthClass(fld)"
>                 align-rule="left"
>                 column-definition="The total amount of food energy in the given serving size.">
>                 {% verbatim %}{{ fld.title }}{% endverbatim %}
>             </mdt-column>
>             <mdt-column ng-show="currLinkObj.hasEdit && currView == 'edit'">.</mdt-column>
>             <mdt-column ng-show="currLinkObj.hasDelete && currView == 'edit'">.</mdt-column>
> 
>         </mdt-header-row> 

The same issue happens with <mdt-cell> within an <mdt-row>

**Comment by faheemhameed** [comment]
Also the ng-show does not work on `<mdt-cell>` within an `<mdt-column>`

>         <mdt-header-row>
>             <mdt-column ng-repeat="fld in currLinkObj.fields"
>                 ng-class="lus.getWidthClass(fld)"
>                 align-rule="left"
>                 column-definition="The total amount of food energy in the given serving size.">
>                 {% verbatim %}{{ fld.title }}{% endverbatim %}
>             </mdt-column>
>             <mdt-column class="icon-edit" ng-show="false">.</mdt-column>
>             <mdt-column class="icon-delete" ng-show="false">.</mdt-column>
>         </mdt-header-row>
> 

The above code does not hide the cell. Also the `ng-hide="true"` does not work as well.

I am switching back to normal `<table>` with `dir-paginate` directive for now.

**Comment by iamisti** [comment]
Thanks for the report. Working on that today, will have results later at the end of this day.

**Comment by faheemhameed** [comment]
Many thanks!!!

**Comment by iamisti** [comment]
The issue is fixed, but other issue come up with the fix. It seems that angular material has a bug and I can't release my fix until it get resolved.
Here is the issue. You guys can help me prioritize this issue by having a +1 on this thread:

https://github.com/angular/material/issues/9275

**Comment by yghelmut** [comment]
Found a quick fix:

var content = clone.html() ? clone.html() : clone.text();
var cellValue = $interpolate(clone.html())($scope.$parent);
